### ISSUE TITLE
crashing on startup

### ISSUE THREAD

**Issue by xemnes** [TeamElysia/ArtisansTabs#6]
trying to load artisans tabs but the game just immediately crashes
im running forge 2316 which is the version given by the conquest reforged launcher as of this current time. as well as liteloader

```
[01:51:39] [Client thread/INFO] [worldedit]: WorldEdit for Forge (version 6.1.4) is loaded
[01:51:39] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from POSTINITIALIZATION to AVAILABLE. Loading cannot continue
[01:51:39] [Client thread/ERROR] [FML]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJ	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJ	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIE	artisans_tabs{1.3.0.0} [Artisan's Tabs] (Artisan's Tabs - v-1.10.2-1.3.0.0.jar) 
	UCHIJ	betterfoliage{2.1.7} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.7.jar) 
	UCHIJ	conquest{2.1.2} [Conquest Reforged] (ConquestReforged-2.1.2-mc1.10.2.jar) 
	UCHIJ	blockpalette{1.4.1} [BlockPalette] (ConquestReforged-2.1.2-mc1.10.2.jar) 
	UCHIJ	com.boydti.fawe{3.5.1} [FastAsyncWorldEdit] (FastAsyncWorldEdit-forge110-17.08.04-1186ca8-791-14.1.22.jar) 
	UCHIJ	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.2-anarchy.jar) 
	UCHIJ	fw{1.5.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.5.0.jar) 
	UCHIJ	itemzoom{1.4} [Item Zoom] (itemzoom1.10.2-1.4.jar) 
	UCHIJ	journeymap{1.10.2-5.4.5} [JourneyMap] (journeymap-1.10.2-5.4.5.jar) 
	UCHIJ	quickhotbar{1.04} [Quick Hotbar] (quickhotbar_1102_1.04.jar) 
	UCHIJ	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJ	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.6-mf-1.10.2-12.18.2.2125.jar) 
[01:51:39] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[01:51:39] [Client thread/ERROR] [FML]: Caught exception from Artisan's Tabs (artisans_tabs)
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at zed.artisanstabs.menu.CustomTabs.destroyTabs(CustomTabs.java:99) ~[CustomTabs.class:?]
	at zed.artisanstabs.menu.gui.ResourcePackMenu.loadMenu(ResourcePackMenu.java:134) ~[ResourcePackMenu.class:?]
	at zed.artisanstabs.menu.gui.ResourcePackMenu.func_110549_a(ResourcePackMenu.java:109) ~[ResourcePackMenu.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) ~[bxi.class:?]
	at zed.artisanstabs.ModRegistry.ModLoader(ModRegistry.java:47) ~[ModRegistry.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616) ~[forge-1.10.2-12.18.3.2316.jar:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[forge-1.10.2-12.18.3.2316.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[forge-1.10.2-12.18.3.2316.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:810) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 41 more
[01:51:40] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.7.jar)
Contact their authors BEFORE contacting forge
```

edit: tried loading minecraft with just artisans tabs and no other mods and it still crashes

**Comment by TheUnknownFew** [comment]
Thank you for submitting a bug. I shall look into this as soon as I get the chance to.

**Comment by TheUnknownFew** [comment]
The issue has been fixed. Thanks again for submitting this bug report.
