### ISSUE TITLE
certain tab creation commands causes errors

### ISSUE THREAD

**Issue by xemnes** [TeamElysia/ArtisansTabs#8]
some of the tab creation commands throws errors and doesnt perform the command, most importantly
`/inbt finalize` cant be used because `/inbt set inv` throws this error:
```
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at zed.artisanstabs.commands.CommandGetNBT.func_184881_a(CommandGetNBT.java:169) ~[CommandGetNBT.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 16 more
[16:49:17] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

```

`/inbt set name` throws this error:

```
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at zed.artisanstabs.commands.CommandGetNBT.func_184881_a(CommandGetNBT.java:162) ~[CommandGetNBT.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[16:52:59] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

```

i havent tried any other commands yet but the error is very similar to the initial crash error i was having where it was related to `scala/actors/threadpool/Arrays`

**Comment by TheUnknownFew** [comment]
Yes, I have realized that I was using the wrong `Arrays` class. I had automatically imported the wrong class, which the right class is from Java Utils. I shall get this fixed in the next update

**Comment by xemnes** [comment]
yeah i was doing some googling, it seems to be common to accidentally import that class lol

**Comment by TheUnknownFew** [comment]
This issue is fixed in all up to date versions. Working on building and uploading the new versions to curseforge. Thank you for bringing this to my attention.
